// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmzironyvdkisefunyik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtemlyb255dmRraXNlZnVueWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjU1ODAsImV4cCI6MjA2MDU0MTU4MH0.wU5rSsb3t7zwpKWUCx_Z_uyw8BTIv1YGCqFva5U-sME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);